language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.0
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 19.3
notifications:
  email: false
